"""
ComfyUI DJB Utils - Custom nodes for ComfyUI
"""

from .image_filename_extractor import NODE_CLASS_MAPPINGS as FILENAME_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as FILENAME_DISPLAY_MAPPINGS
from .resolution_detector import NODE_CLASS_MAPPINGS as RESOLUTION_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as RESOLUTION_DISPLAY_MAPPINGS

# Combine all node mappings
NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

# Add filename extractor nodes
NODE_CLASS_MAPPINGS.update(FILENAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(FILENAME_DISPLAY_MAPPINGS)

# Add resolution detector nodes
NODE_CLASS_MAPPINGS.update(RESOLUTION_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(RESOLUTION_DISPLAY_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
